backend:
  name: github
  repo: frm/mendes.codes

media_folder: static/assets
public_folder: /assets

collections:
  - name: settings
    label: Settings
    files:
      - name: config
        label: Config
        file: site-meta-data.json
        fields:
          - widget: string
            name: title
            label: Site Title
            required: true
          - widget: string
            name: siteUrl
            label: Website URL
            required: true
          - widget: text
            name: description
            label: Description
            default: ''
            required: false
          - widget: object
            name: socials
            label: Socials
            fields:
              - widget: text
                name: twitter
                description: Twitter URL
                required: true
              - widget: text
                name: github
                description: GitHub URL
                required: true
              - widget: text
                name: email
                description: Email
                required: true
          - widget: object
            name: links
            label: Links
            fields:
              - widget: text
                name: subvisual
                description: Subvisual URL
                required: true
              - widget: text
                name: thoughtbot
                description: thoughtbot URL
                required: true
              - widget: text
                name: utrust
                description: Utrust URL
                required: true
              - widget: text
                name: include
                description: "#include <braga> URL"
                required: true
              - widget: text
                name: coderdojo
                description: CoderDojo URL
                required: true
              - widget: text
                name: rubyconfpt
                description: RubyConfPT URL
                required: true
              - widget: text
                name: mirrorconf
                description: MirrorConf URL
                required: true
              - widget: text
                name: bragajs
                description: Braga.js URL
                required: true
              - widget: text
                name: bragabeam
                description: Braga.BEAM URL
                required: true
          - widget: list
            name: talks
            label: Talks
            allow_add: true
            fields:
              - {name: title, label: Title, widget: string, required: true}
              - {name: event, label: Event, widget: string, required: true}
              - {name: description, label: Description, widget: text, required: true}
              - {name: videoId, label: "Video ID", widget: string, required: true}
              - {name: slidesUrl, label: "Slides URL", widget: string, required: true}
              - name: variation
                label: Variation
                widget: object
                fields:
                  - name: title
                    label: Title
                    widget: string
                    required: true
                  - name: url
                    label: URL
                    widget: string
                    required: true

  # - name: blog
  #   label: Blog
  #   folder: _data/blog
  #   slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
  #   create: true
  #   fields:
  #     - {
  #         label: Template,
  #         name: template,
  #         widget: hidden,
  #         default: BlogPost,
  #       }
  #     - name: path
  #       label: Path
  #       widget: string
  #       pattern: [/]
  #       hint: "Path must start with /"
  #     - { name: date, label: Date, widget: datetime }
  #     - { name: title, label: Title }
  #     - label: Meta Description
  #       name: metaDescription
  #       widget: text
  #       required: false
  #     - label: Featured Image
  #       name: thumbnail
  #       widget: image
  #       hint: "Image size 1280x800 works best :)"
  #       required: false
  #       media_library:
  #         config:
  #           multiple: false
  #     - { name: body, label: Body, widget: markdown }
